name: CI/CD Deploy to k3s

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. CI: Проверка манифестов (Lint)
      - name: Check YAML (lint)
        run: |
          kubectl apply --dry-run=client -f k8s/

      # 2. CI: Сборка образа (чтобы убедиться, что Dockerfile рабочий)
      - name: Build Docker image
        run: |
          docker build -t myapp:${{ github.sha }} .

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test # Деплой начнется ТОЛЬКО если проверки выше прошли успешно
    steps:
      - name: SSH & Deploy to k3s
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: zhlbn42
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Обновляем код на сервере (если там развернут git) или просто пушим манифесты
            cd /home/zhlbn42/kuber
            git pull origin main || echo "Not a git repo, skipping pull"
            
            # Применяем изменения
            cd k8s
            kubectl apply -f .
            
            # Проверяем статус
            kubectl get pods
